### PR TITLE
Value changes when new props is given

### PR DESCRIPTION
**Pull request by mattyx96**

### CODE REVIEW

**Comment by himelbrand** [comment]
@mattyx96  please explain what this PR will add to the library.
I need to understand your change before I'll merge

**Comment by mattyx96** [comment]
I added 2 lines for the value number string update when new props passed without unmount the component in componentDidUpdate of numericInput.js

**Comment by himelbrand** [comment]
@mattyx96 
have you tested to check that the original functionality remained intact ?

**Comment by mattyx96** [comment]
@himelbrand
I m using the modified library on an app and all seems to work well

**Comment by himelbrand** [comment]
@mattyx96 merged!
thank you for contributing.

**Pull request merged**
