### PR TITLE
Replacing Deprecated componentWillReceiveProps

### LINKED ISSUE #47: [BUG] - Warning notice about using "componentWillReceiveProps" as unsafe component function
**Describe the bug**
Warning notice about using `componentWillReceiveProps` as unsafe component function.

**To Reproduce**
`componentWillReceiveProps` used in file `NumericInput.js`
```
    componentWillReceiveProps(props) {
        const initSent = !(props.initValue !== 0 && !props.initValue)
        if (props.initValue !== this.state.value && initSent) {

            this.setState({
                value: props.initValue,
                lastValid: props.initValue,
                stringValue: props.initValue.toString()
            });
        }
    }
```

**Enviorment:**
 - Version: 1.8.3
 - React: 16.9.0
 - React Native version: 0.61.2
 - Device: Emulator Android 5.1.0

### PR DESCRIPTION
**Pull request by Bilal-Abdeen**
This fixes #47 

/*
    // Bilal Abdeen deleted the following method componentWillReceiveProps()
    //      and replaced it with the method componentDidUpdate() below.
    componentWillReceiveProps(props) {
        const initSent = !(props.initValue !== 0 && !props.initValue)

        if (props.initValue !== this.state.value && initSent) {
            this.setState({
                value: props.initValue,
                lastValid: props.initValue,
                stringValue: props.initValue.toString()
            });
        }
    }
// */

//*
    // Bilal Abdeen added the following method componentDidUpdate() 
    //      as a replacement for the method componentWillReceiveProps() above. 
    // this.props refers to the new props
    componentDidUpdate() {
        const initSent = !(this.props.initValue !== 0 && !this.props.initValue); 

        // compare the new value (props.initValue) with the existing/old one (this.state.value)
        if (this.props.initValue !== this.state.value && initSent) {
            this.setState({
                value: this.props.initValue,
                lastValid: this.props.initValue,
                stringValue: this.props.initValue.toString()
            });
        }
    }
// */

### CODE REVIEW

**Comment by himelbrand** [comment]
Hi, thanks for the PR @Bilal-Abdeen 
did you test it and it works properly without breaking?

seems ok, just to make sure before I approve this PR.

**Comment by Bilal-Abdeen** [comment]
I have NOT done extensive testing. I am still learning about React and React-Native. I have done this change in my 1st ever React-Native project. It has been working fine, since the change.

**Comment by 3xpedia** [comment]
Hi,
Quickly tested on my side : looks ok.
Any plan to merge this PR?

Thanks

**Comment by mthomas-github** [comment]
I've tested this as well, any plans to merge?

**Comment by 3xpedia** [comment]
> I've tested this as well, any plans to merge?

The component looks like not being updated for a while.
I'm considering making a fork to host updates :)

**Pull request merged**
